apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api
  name: api
  namespace: api
spec:
  serviceAccountName: api-sa
  containers:
  - image: alpine:3.12
    name: api
    command:
    - sh
    - -c
    - sleep 1d